# Restricted Boltzmann Machines - Sistemas de Recomendação

In [1]:
import import_ipynb
import rbm
from rbm import RBM

import numpy as np

importing Jupyter notebook from rbm.ipynb


## Obter os dados

In [2]:
# Base de dados com os preferências utilizadores
# 1: Gostou do filme
# 0: Não viu o filme

base = np.array([[1,1,1,0,0,0],
                 [1,0,1,0,0,0],
                 [1,1,1,0,0,0],
                 [0,0,1,1,1,1],
                 [0,0,1,1,0,1],
                 [0,0,1,1,0,1]])

In [3]:
# Nomes dos filmes
# Utilizador 1: Gostou de  "A bruxa", "Invocação do mal", "O chamado" e não viu os outros 3
filmes = ["A bruxa", "Invocação do mal", "O chamado",
          "Se beber não case", "Gente grande", "American pie"]

## Modelo da Restricted Boltzmann Machine

In [4]:
# num_visible: nº de neurónios na camada de entrada, neste caso 6 filmes
# num_hidden: nº de neurónios na camada escondida

model = RBM(num_visible= 6, num_hidden=2)

In [5]:
# Processo de treino
# Multiplicar os valores da camada de entrada pelos pesos(definidos aleatoriamente) para se obter os valores da camada oculta.
# Com os valores da camada oculta reconstruir os valores da camada de entrada(registros)
# Com os novos valores da camada de entrada obter os valores da camada oculta(multiplicando esses valores pelos pesos).
# Com os novos valores da camada oculta reconstruir os valores da camada de entrada.
# Estes passos são repetidos até um determinado numero de épocas ou até os registros obtidos na ultima iteração serem iguais 
# aos registros originais.
# A reconstrução dos nós é feita utilizando a técnica de gibbs sampling.
# Cada nó da camada de entrada é reconstruido utilizando todos os nós da camada oculta.
# Os pesos não são actualizados durante os calculos. Os pesos aleatorios definidos no inicio mantêm-se durante todo o processo. 
# Só são actualizados no fim do processo(depois de todas as épocas ou depois dos registros obtidos na ultima epoca serem iguais
# aos registros originais).

# treinar o modelo com os dados.
model.train(base, max_epochs=5000)

Epoch 0: error is 9.127629798495681
Epoch 1: error is 8.89452570677716
Epoch 2: error is 8.791310670801176
Epoch 3: error is 8.604091139093352
Epoch 4: error is 8.392940311623631
Epoch 5: error is 8.29318769697494
Epoch 6: error is 8.170797622211369
Epoch 7: error is 8.155153185972567
Epoch 8: error is 8.047964838813874
Epoch 9: error is 7.832943403160492
Epoch 10: error is 7.7182889263309455
Epoch 11: error is 7.837760397067697
Epoch 12: error is 7.641407520863941
Epoch 13: error is 7.693437742139826
Epoch 14: error is 7.5069825954253915
Epoch 15: error is 7.287177462428535
Epoch 16: error is 7.406994901097987
Epoch 17: error is 7.4607477844002545
Epoch 18: error is 7.288899205117229
Epoch 19: error is 7.237323375327979
Epoch 20: error is 7.468544685980408
Epoch 21: error is 7.3244983015884415
Epoch 22: error is 7.478172667233894
Epoch 23: error is 7.180827914049043
Epoch 24: error is 7.223955199120171
Epoch 25: error is 7.215119312581537
Epoch 26: error is 7.017563740728214
Epoch 27:

Epoch 405: error is 1.716391444565307
Epoch 406: error is 2.034270709187394
Epoch 407: error is 1.7080120191254962
Epoch 408: error is 1.7026043416649117
Epoch 409: error is 2.280752770402063
Epoch 410: error is 1.4368758033126048
Epoch 411: error is 1.6896110532222934
Epoch 412: error is 1.6845844844185407
Epoch 413: error is 1.7015488176957634
Epoch 414: error is 1.4187582441504099
Epoch 415: error is 1.4129890718157736
Epoch 416: error is 1.666819636877791
Epoch 417: error is 1.4044513571683037
Epoch 418: error is 1.6589948786378927
Epoch 419: error is 1.3961655953438086
Epoch 420: error is 2.1710401801806527
Epoch 421: error is 1.6448997661778182
Epoch 422: error is 1.3862155932328524
Epoch 423: error is 2.2657331596033
Epoch 424: error is 1.3753285841293605
Epoch 425: error is 2.176868478549377
Epoch 426: error is 1.6251996705023612
Epoch 427: error is 1.3640563554393321
Epoch 428: error is 3.4186964533358917
Epoch 429: error is 1.6154950695471495
Epoch 430: error is 2.25849559521

Epoch 873: error is 1.3587706453551236
Epoch 874: error is 1.7905335280946981
Epoch 875: error is 1.357891122835911
Epoch 876: error is 1.3576872977093735
Epoch 877: error is 1.0419874526294903
Epoch 878: error is 1.3581410001358283
Epoch 879: error is 1.3579194999898143
Epoch 880: error is 1.3577054457725757
Epoch 881: error is 1.3574985559873802
Epoch 882: error is 2.2823666623623606
Epoch 883: error is 1.3579602251173308
Epoch 884: error is 1.3577356542793568
Epoch 885: error is 1.3575186876977245
Epoch 886: error is 1.357309038354123
Epoch 887: error is 1.357106429224685
Epoch 888: error is 1.3569105930122425
Epoch 889: error is 1.3567212718799588
Epoch 890: error is 1.3565382171868536
Epoch 891: error is 1.3563611892256782
Epoch 892: error is 1.3561899569635651
Epoch 893: error is 1.3560242977858192
Epoch 894: error is 1.3558639972431907
Epoch 895: error is 1.3557088488029176
Epoch 896: error is 1.355558653603803
Epoch 897: error is 1.35541322021555
Epoch 898: error is 1.355272364

Epoch 1380: error is 1.358345561434627
Epoch 1381: error is 1.3576793059900631
Epoch 1382: error is 1.357036427893227
Epoch 1383: error is 0.8969957277425196
Epoch 1384: error is 1.3577038902383336
Epoch 1385: error is 1.3570592666975467
Epoch 1386: error is 1.356437403277573
Epoch 1387: error is 0.8979308803346266
Epoch 1388: error is 1.3571149347960658
Epoch 1389: error is 1.3564902303155766
Epoch 1390: error is 1.3558877111201666
Epoch 1391: error is 1.355306726613536
Epoch 1392: error is 1.3547466370999193
Epoch 1393: error is 1.3542068141879364
Epoch 1394: error is 1.3536866411427004
Epoch 1395: error is 1.3531855131888544
Epoch 1396: error is 1.3527028377671992
Epoch 1397: error is 0.9071452924556184
Epoch 1398: error is 1.35342750499134
Epoch 1399: error is 1.3529350721498936
Epoch 1400: error is 1.3524608251416756
Epoch 1401: error is 0.9073366989849697
Epoch 1402: error is 1.353187997964648
Epoch 1403: error is 1.3527035897603021
Epoch 1404: error is 1.3522371210534008
Epoch 1

Epoch 1817: error is 1.3781289824229657
Epoch 1818: error is 1.3768292690258137
Epoch 1819: error is 1.3755676782028736
Epoch 1820: error is 0.8144089675196972
Epoch 1821: error is 0.8121561107166697
Epoch 1822: error is 1.3774008597799388
Epoch 1823: error is 1.3761238074667674
Epoch 1824: error is 1.3748845313426894
Epoch 1825: error is 0.8150158326937624
Epoch 1826: error is 0.8127307782638301
Epoch 1827: error is 0.8105144264413114
Epoch 1828: error is 0.8083642699182441
Epoch 1829: error is 1.379802116650212
Epoch 1830: error is 1.3784581176641149
Epoch 1831: error is 1.3771529408938523
Epoch 1832: error is 1.3758860031078923
Epoch 1833: error is 1.3746566995292213
Epoch 1834: error is 0.8147015077128024
Epoch 1835: error is 0.8124026789022266
Epoch 1836: error is 0.8101730574444884
Epoch 1837: error is 1.378056551996258
Epoch 1838: error is 0.8096982370130764
Epoch 1839: error is 0.8075448428733006
Epoch 1840: error is 1.3798321268649383
Epoch 1841: error is 0.8071456606485489
Ep

Epoch 2391: error is 1.4985535650372237
Epoch 2392: error is 1.4956294499012515
Epoch 2393: error is 0.7088616981309436
Epoch 2394: error is 1.6241440527207278
Epoch 2395: error is 0.7073913033348869
Epoch 2396: error is 0.7071855054204543
Epoch 2397: error is 0.7069830135625992
Epoch 2398: error is 0.7067837574290178
Epoch 2399: error is 0.7065876684664157
Epoch 2400: error is 0.7063946798478857
Epoch 2401: error is 0.7062047264220701
Epoch 2402: error is 0.706017744664036
Epoch 2403: error is 0.7058336726278032
Epoch 2404: error is 0.705652449900457
Epoch 2405: error is 0.7054740175577928
Epoch 2406: error is 1.50468026787831
Epoch 2407: error is 0.7060171752663507
Epoch 2408: error is 0.7058306134685914
Epoch 2409: error is 0.7056469543396341
Epoch 2410: error is 1.503620510024065
Epoch 2411: error is 1.5006967982251578
Epoch 2412: error is 0.7069638225919549
Epoch 2413: error is 1.4984397712304527
Epoch 2414: error is 0.7075491080868914
Epoch 2415: error is 0.7073307364409589
Epoch

Epoch 2786: error is 0.692989284129218
Epoch 2787: error is 1.530104925659503
Epoch 2788: error is 0.693424635785426
Epoch 2789: error is 0.6933197066018071
Epoch 2790: error is 0.6932161435899084
Epoch 2791: error is 0.6931139226900491
Epoch 2792: error is 0.693013020347638
Epoch 2793: error is 0.6929134135007086
Epoch 2794: error is 0.6928150795678079
Epoch 2795: error is 0.6927179964362308
Epoch 2796: error is 0.6926221424505848
Epoch 2797: error is 0.6925274964016791
Epoch 2798: error is 0.6924340375157226
Epoch 2799: error is 0.6923417454438259
Epoch 2800: error is 0.6922506002517949
Epoch 2801: error is 0.6921605824102067
Epoch 2802: error is 0.692071672784762
Epoch 2803: error is 0.6919838526268999
Epoch 2804: error is 0.6918971035646728
Epoch 2805: error is 0.6918114075938699
Epoch 2806: error is 0.6917267470693821
Epoch 2807: error is 0.691643104696801
Epoch 2808: error is 2.4597570309596457
Epoch 2809: error is 0.6914788069344131
Epoch 2810: error is 0.6913981186368289
Epoch 

Epoch 3334: error is 0.6806372763119766
Epoch 3335: error is 0.680618729658677
Epoch 3336: error is 1.5804300371481048
Epoch 3337: error is 0.6807597262979065
Epoch 3338: error is 0.6807395834585256
Epoch 3339: error is 0.6807195671384209
Epoch 3340: error is 0.6806996759388244
Epoch 3341: error is 0.6806799084790436
Epoch 3342: error is 0.6806602633961966
Epoch 3343: error is 0.6806407393449505
Epoch 3344: error is 0.6806213349972681
Epoch 3345: error is 0.680602049042153
Epoch 3346: error is 0.6805828801854049
Epoch 3347: error is 0.6805638271493752
Epoch 3348: error is 0.6805448886727277
Epoch 3349: error is 0.6805260635102031
Epoch 3350: error is 0.6805073504323894
Epoch 3351: error is 0.6804887482254932
Epoch 3352: error is 0.680470255691116
Epoch 3353: error is 1.5805613709881072
Epoch 3354: error is 0.6806129740070367
Epoch 3355: error is 0.6805928798467222
Epoch 3356: error is 0.6805729129598631
Epoch 3357: error is 0.6805530719413432
Epoch 3358: error is 0.6805333554041647
Epo

Epoch 3766: error is 0.6778558149932872
Epoch 3767: error is 0.6778362457919562
Epoch 3768: error is 0.6778168173720868
Epoch 3769: error is 0.6777975282207457
Epoch 3770: error is 1.581877779855861
Epoch 3771: error is 0.6779771146343068
Epoch 3772: error is 0.6779561032923554
Epoch 3773: error is 0.6779352486953675
Epoch 3774: error is 1.5801979198453049
Epoch 3775: error is 0.6781261170812021
Epoch 3776: error is 0.67810342713086
Epoch 3777: error is 0.6780809127742754
Epoch 3778: error is 0.678058572053817
Epoch 3779: error is 0.6780364030376461
Epoch 3780: error is 0.678014403819312
Epoch 3781: error is 1.6236620994156366
Epoch 3782: error is 0.6777487323684956
Epoch 3783: error is 0.6777294096666133
Epoch 3784: error is 0.6777102254305216
Epoch 3785: error is 0.6776911781783558
Epoch 3786: error is 0.6776722664468395
Epoch 3787: error is 0.6776534887910115
Epoch 3788: error is 2.5649783490645186
Epoch 3789: error is 0.6772457664589967
Epoch 3790: error is 0.6772309141843353
Epoch

Epoch 4180: error is 0.6751185362072939
Epoch 4181: error is 0.6751074723214898
Epoch 4182: error is 0.6750964710360431
Epoch 4183: error is 0.675085531789767
Epoch 4184: error is 0.675074654027291
Epoch 4185: error is 0.67506383719899
Epoch 4186: error is 1.5953580737704334
Epoch 4187: error is 0.6751866631860989
Epoch 4188: error is 0.6751748124398109
Epoch 4189: error is 0.6751630317184976
Epoch 4190: error is 0.6751513203838306
Epoch 4191: error is 0.6751396778042381
Epoch 4192: error is 0.675128103354819
Epoch 4193: error is 0.6751165964172621
Epoch 4194: error is 0.6751051563797632
Epoch 4195: error is 0.6750937826369462
Epoch 4196: error is 0.6750824745897837
Epoch 4197: error is 0.6750712316455191
Epoch 4198: error is 0.6750600532175904
Epoch 4199: error is 0.6750489387255556
Epoch 4200: error is 0.6750378875950167
Epoch 4201: error is 0.6750268992575482
Epoch 4202: error is 1.5951336111579173
Epoch 4203: error is 0.6751520186566039
Epoch 4204: error is 0.6751399809392361
Epoch

Epoch 4746: error is 0.6724214534793386
Epoch 4747: error is 0.6724180392325511
Epoch 4748: error is 0.6724146314460167
Epoch 4749: error is 0.6724112300852282
Epoch 4750: error is 0.6724078351159035
Epoch 4751: error is 0.672404446503986
Epoch 4752: error is 0.6724010642156424
Epoch 4753: error is 0.6723976882172616
Epoch 4754: error is 0.6723943184754548
Epoch 4755: error is 0.6723909549570529
Epoch 4756: error is 0.6723875976291057
Epoch 4757: error is 0.6723842464588812
Epoch 4758: error is 0.6723809014138646
Epoch 4759: error is 0.672377562461756
Epoch 4760: error is 0.6723742295704705
Epoch 4761: error is 0.6723709027081365
Epoch 4762: error is 0.6723675818430943
Epoch 4763: error is 0.6723642669438958
Epoch 4764: error is 0.6723609579793022
Epoch 4765: error is 1.6176325367840672
Epoch 4766: error is 0.6723871741149005
Epoch 4767: error is 0.6723836553126736
Epoch 4768: error is 0.6723801439058444
Epoch 4769: error is 0.6723766398555151
Epoch 4770: error is 0.6723731431229893
Ep

In [6]:
# Pesos obtidos
# 1º coluna e 1º linha: bias
# 1º filme "A bruxa"           (1º neuronio: -3.34840008, 2º neuronio:  7.9484309)
# 2º filme "Invocação do mal"  (1º neuronio: -7.24214558, 2º neuronio:  3.33698676) 
# 3º filme "O chamado"         (1º neuronio:  3.81603103, 2º neuronio:  1.82698867)
# 4º filme "Se beber não case" (1º neuronio:  3.62763285, 2º neuronio: -8.24125544)
# 5º filme "Gente grande"      (1º neuronio:  0.60819574, 2º neuronio: -4.55321246)
# 6º filme "American pie"      (1º neuronio:  3.62379602, 2º neuronio: -8.24384883)

# Pela análise dos pesos nota-se que o 2º neurónio é especalista esm detectar filmes de terror(tem números possitivos para
# as pessoas que viram esses filmes) e o 1º neurónio é especialista em detectar filmes de comédia(tem números possitivos para
# as pessoas que viram esses filmes).

model.weights

array([[ 2.47553888,  2.2883063 ,  0.36837755],
       [-1.00678384, -3.3007235 ,  7.94235342],
       [ 0.23325868, -7.2586987 ,  3.33239578],
       [ 4.9473473 ,  3.86092139,  1.86844415],
       [ 0.95811799,  3.61943098, -8.23986146],
       [-1.31240262,  0.60750439, -4.55319261],
       [ 0.96327482,  3.61548462, -8.24242571]])

## Recomendação de filmes

In [7]:
# Processo de recomendação
# Partindo do principio que durante o treino do algoritmo encontrou-se 1 nó para filmes de terror e outro nó para filmes de 
# comédia.
# Para 1 registro com os seguintes dados: 1_100_ (ou seja gostou de 2 filmes de terror e não gostou de 2 filmes de comédia).
# Não viu um dos filmes de terror e 1 dos filmes de comédia.

# Compara-se os neuronios da camada de entrada, com os filmes que a pessoa viu, com os neuronios da camada oculta. 
# Ligam-se os filmes A bruxa e o chamado(filmes de terror vistos) ao neurónio dos filmes de terror. Como a pessoa gostou desses
# 2 filmes esse neurónio é activado(fica verde).
# Ligam-se os filmes Se beber não case, Gente grande(filmes de comédia que a pessoa viu) ao neurónio dos filmes de comédia. 
# Como a pessoa não gostou desses filmes esse neurónio é desactivado(fica vermelho).
# Para o filmes não vistos, identifica-se se pertence a terror ou comédia e se os neurónios da camada oculta estão actidos ou
# desactivados.
# Para o Invocação do mal, como é um filme de terror vai estar ligado apenas ao neurónio de terror. Como o neurónio de terror 
# está activo(verde) vai retornar o valor 1 para a camada de entrada(ou seja o filme vai ser recomendado).
# Para o American Pie, como é um filme de comédia vai estar ligado apenas ao neurónio de comédia. Como o neurónio de comédia
# está desactivo(vermelho) vai retornar o valor 0 para a camada de entrada(ou seja o filme não vai ser recomendado).

user1 = np.array([[1,1,0,1,0,0]])
user2 = np.array([[0,0,0,1,1,0]])

In [8]:
# Indica o neurónio que é activado para os filmes vistos pelo utilizador.
# Como o user viu mais filmes de terror, o 2º neurónio é activado.
model.run_visible(user1)

array([[0., 1.]])

In [9]:
# Como o user viu filmes de comédia, o 1º neurónio é activado.
model.run_visible(user2)

array([[1., 0.]])

In [10]:
# Recomendação para o user 1

# Para o filmes não vistos, identifica-se se pertence a terror ou comédia e se os neurónios da camada oculta estão actidos ou
# desactivados.
# Como o neurónio de terror está activo(verde) vai retornar o valor 1 para a camada de entrada(ou seja o filme de terror que
# ainda não foi visto vai ser recomendado).

hidden_layer_user1 = np.array([[0,1]])
recomendation_user1 = model.run_hidden(hidden_layer_user1)
recomendation_user1

array([[1., 1., 1., 0., 0., 0.]])

In [11]:
# Recomendação para o user 2

# Para o filmes não vistos, identifica-se se pertence a terror ou comédia e se os neurónios da camada oculta estão actidos ou
# desactivados.
# Como o neurónio de comédia está activo(verde) vai retornar o valor 1 para a camada de entrada(ou seja o filme de comédia que
# ainda não foi visto vai ser recomendado).

hidden_layer_user2 = np.array([[1,0]])
recomendation_user2 = model.run_hidden(hidden_layer_user2)
recomendation_user2

array([[0., 0., 1., 1., 0., 1.]])

In [12]:
# Função com os filmes recomendados para o utilizador 1.
for i in range(len(user1[0])): # tamanho da lista de filmes
    #print(user1[0,i])
    if user1[0,i] == 0 and recomendation_user1[0,i] == 1:
        print("Filmes recomendados:", filmes[i])

Filmes recomendados: O chamado


In [13]:
# Função com os filmes recomendados para o utilizador 2.
for i in range(len(user1[0])): # tamanho da lista de filmes
    #print(user2[0,i])
    if user2[0,i] == 0 and recomendation_user2[0,i] == 1:
        print("Filmes recomendados:", filmes[i])

Filmes recomendados: O chamado
Filmes recomendados: American pie
