In [1]:
import tensorflow as tf

In [2]:
tf.VERSION

'1.13.1'

# Variaveis, Constantes e Marcadores de posição(Placeholders) no TensorFlow 1.x

## Variaveis e Constantes

In [4]:
one = tf.constant(1)

In [5]:
print(one)

Tensor("Const:0", shape=(), dtype=int32)


In [6]:
ten=tf.Variable(10)

Instructions for updating:
Colocations handled automatically by placer.


In [13]:
# Metodo add
# sum = ten+one
sum = tf.add(ten,one)

In [14]:
# Metodo updade
# update ten=sum, como ten é uma variavel é possivel atribuir-lhe um novo valor, neste caso 11(10+1)
update = tf.assign(ten,sum)

In [15]:
# Se estiver-se a utilizar variaveis é necessário esta linha de codigo
# Caso se utilizem constantes e placeholders não é necessário

init_op = tf.global_variables_initializer()

In [16]:
sess = tf.Session()

In [17]:
sess.run(init_op)

In [21]:
print(sess.run(update))

12


In [22]:
print(sess.run(sum))

13


## Placeholders

In [26]:
#Não são iniciados com valores - ao contrario das constantes e variavies
a = tf.placeholder(tf.float32)

In [27]:
a

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>

In [31]:
b = a*2

In [32]:
sess.run(b, feed_dict={a:3.0})

6.0

In [33]:
sess.run(b, feed_dict={a:[1,2,3,4]})

array([2., 4., 6., 8.], dtype=float32)

In [34]:
dict = {a:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}

In [36]:
result = sess.run(b, feed_dict=dict)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]
  [26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


### Multiplos Placeholders

In [37]:
a = tf.placeholder(tf.float32)

In [38]:
b = tf.placeholder(tf.float32)

In [39]:
c=a+b

In [41]:
sess = tf.Session()

In [43]:
result = sess.run(c, feed_dict={a:10,b:5})
print(result)

15.0


In [46]:
# d=a*(a+b)
d=a*c

In [48]:
result = sess.run(d, feed_dict={a:10,b:20})
print(result)

300.0


In [49]:
avalues = [1,2,3]
bvalues = [4,5,6]

In [51]:
# c = a+b
result = sess.run(c, feed_dict={a:avalues,b:bvalues})
print(result)

[5. 7. 9.]


In [53]:
# d = a*(a+b)
result = sess.run(d, feed_dict={a:avalues,b:bvalues})
print(result)

[ 5. 14. 27.]
